version: 0.2

env:
  variables:
    account: "Data Enablement DEV"
    
batch:
  fast-fail: true
  build-list:
    - identifier: de_shared_postgresql_dev
      buildspec: pilot-databases/migrations/postgres/de-shared-postgresql-dev.yaml
